### ISSUE TITLE
Error: "[WARNING] Ignoring an unsupported file of type 0020000"

### ISSUE THREAD

**Issue by Dibbyo456** [DDoSolitary/LxRunOffline#99]
**System Info:**

- Windows 10 Build 1903 (everything is up to date)
- LxRunOffline v3.40 (installed via chocolatey)

**Command that I ran**:
````bash
LxRunOffline i -n ubuntu1604main -d "C:\ubuntu1604main" -f "C:\Users\HARRY\Downloads\Compressed\16.04.2-server-cloudimg-amd64-root.tar.gz" -s
````

**Error log**:

````bash
[WARNING] Ignoring an unsupported file "dev/midi01" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/null" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty7" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty0" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop3" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/mixer" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/rmidi3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/audioctl" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram2" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/tty6" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/rmidi0" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop6" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/midi03" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram6" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/tty5" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/midi2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop4" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/agpgart" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/random" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/mpu401stat" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/dsp" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/kmem" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/midi0" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop1" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/loop2" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/ram5" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/port" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/mapper/control" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/audio3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram14" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/audio2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram0" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/audio1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/sequencer" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/dsp2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty4" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop0" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/tty9" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/smpte1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/rmidi2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram8" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/mixer1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop7" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/midi1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty8" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/urandom" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram11" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/tty1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/rmidi1" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/audio" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram12" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/mpu401data" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/console" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/mixer3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/smpte3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram3" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/midi3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram13" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/dsp3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/smpte2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram4" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/mixer2" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram1" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/full" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram7" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/midi02" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/mem" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/sndstat" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/midi00" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram10" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/smpte0" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/tty3" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/loop5" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/ram15" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/ram16" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/zero" of type 0020000.
[WARNING] Ignoring an unsupported file "dev/ram9" of type 0060000.
[WARNING] Ignoring an unsupported file "dev/dsp1" of type 0020000.
[WARNING] Love this tool? Would you like to make a donation: https://github.com/DDoSolitary/LxRunOffline/blob/master/README.md#donation
````

**Comment by DDoSolitary** [comment]
It's not an error. The program has successfully run to completion. All of these output are warnings because the tar archive contains some device files that can't be properly extracted. There is no need to worry because necessary device files will be automatically created when you run the installed distro.

**Comment by Dibbyo456** [comment]
Ah. That's very good to hear. I was wondering the same. Even though I got a lot of warning, everything is working perfectly fine. Closing the ticket and thank you for quick reply. 😘

**Comment by lucvdv** [comment]
Is this true for all device files?
I moved Ubuntu 20.04 on Server 2019, v 1809 to another folder with 'LxRunOffline m'.

This error was given for /dev/console, /dev/full, /dev/mapper/control and /dev/ptmx, and none of these exist after the move.
I tried to hack a partial fix by creating a symlink /dev/console to /dev/tty, but that disappeared after a reboot.

There were some other devices giving the error too, including /dev/null and /dev/tty, but those came back as you said.

**Comment by DDoSolitary** [comment]
The device files alone are useless. On a real Linux system, these files are not stored on a disk but directly provided by the kernel. If you don't see these files in WSL, it's simply because WSL doesn't support them.

**Comment by lucvdv** [comment]
> @lucvdv The device files alone are useless. On a real Linux system, these files are not stored on a disk but directly provided by the kernel. If you don't see these files in WSL, it's simply because WSL doesn't support them.

Yes, that's what I thought too, but then I was wondering why the files are present in a disk image.
Are you accessing them _through_ WSL when you are copying, so I shouldn't regard the system as stopped?

Besides that, I found a WSL issue from 2018 about the missing /dev/full that was acknowledged as something they were already working on, so I thought that would have been fixed by now.

**Comment by DDoSolitary** [comment]
@lucvdv 

> Yes, that's what I thought too, but then I was wondering why the files are present in a disk image.

I don't know. These images are provided by distro maintainers rather than me.

> so I thought that would have been fixed by now.

No, it's not fixed. However, you can use WSL2, which doesn't have this bug at all because it uses a real Linux kernel.

**Comment by lucvdv** [comment]
> However, you can use WSL2
Thanks for taking the time to explain things.
WSL2 is (still, for the moment) not an option for another reason, I still need VMWare Workstation, and that's mutually exclusive with everything powered by HyperV.

**Comment by amzon-ex** [comment]
> @lucvdv
> 
> > Yes, that's what I thought too, but then I was wondering why the files are present in a disk image.
> 
> I don't know. These images are provided by distro maintainers rather than me.
> 
> > so I thought that would have been fixed by now.
> 
> No, it's not fixed. However, you can use WSL2, which doesn't have this bug at all because it uses a real Linux kernel.

This might be a stupid question, but how to import a tarball as WSL2 distro?

**Comment by DDoSolitary** [comment]
@amzon-ex this project currently doesn't support installing WSL2 distros directly, you can 1) install as WSL1 and then convert to WSL2, or 2) use `wsl --import`
